import { Router } from "express";
import authRoutes from  "./auth.routes.js";
import userRoutes from "./user.routes.js";
import productRoutes from "./product.routes.js";
import cartRoutes from "./cart.routes.js";
import orderRoutes from "./order.routes.js";
import paymentRoutes from "./payment.routes.js";
const router = Router();
router.use("/products",productRoutes);
router.use("/auth",authRoutes);
router.use("/user",userRoutes);
router.use("/cart",cartRoutes);
router.use("/order",orderRoutes);
router.use("/payments",paymentRoutes);
export default router;